"""Add category to financial_data

Revision ID: b5068dbe0d01
Revises: fe91f7e3bb62
Create Date: 2024-06-05 16:36:00.478791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5068dbe0d01'
down_revision = 'fe91f7e3bb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.drop_column('target')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
