"""Add target column to FinancialData

Revision ID: fe91f7e3bb62
Revises: a9c390270e6f
Create Date: 2024-05-30 16:14:33.322349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe91f7e3bb62'
down_revision = 'a9c390270e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.drop_column('target')

    # ### end Alembic commands ###
